import type { Habitant, Task } from './types'

export const initialHabitants: Habitant[] = [
  {
    id: '1',
    name: 'Mamá',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mama&backgroundColor=ffd5dc',
    xp: 450,
  },
  {
    id: '2',
    name: 'Papá',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=papa&backgroundColor=c0aede',
    xp: 380,
  },
  {
    id: '3',
    name: 'Carlos',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=carlos&backgroundColor=b6e3f4',
    xp: 220,
  },
  {
    id: '4',
    name: 'Lucía',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lucia&backgroundColor=d1d4f9',
    xp: 195,
  },
]

export const initialTasks: Task[] = [
  {
    id: '1',
    title: 'Lavar los platos',
    description: 'No olvidar las ollas grandes',
    assigneeId: '3',
    completed: false,
    color: 'yellow',
    rotation: -2,
    createdAt: new Date(),
    difficulty: 'básica',
  },
  {
    id: '2',
    title: 'Pasear al perro',
    description: 'Paseo de 20 minutos por el parque',
    assigneeId: '4',
    completed: false,
    color: 'pink',
    rotation: 3,
    createdAt: new Date(),
    difficulty: 'intermedia',
  },
  {
    id: '3',
    title: 'Comprar leche',
    description: 'También comprar pan y huevos',
    assigneeId: '1',
    completed: false,
    color: 'blue',
    rotation: -1,
    createdAt: new Date(),
    difficulty: 'básica',
  },
  {
    id: '4',
    title: 'Sacar la basura',
    description: 'Recordar reciclar el cartón',
    assigneeId: '2',
    completed: true,
    color: 'green',
    rotation: 2,
    createdAt: new Date(),
    difficulty: 'básica',
  },
  {
    id: '5',
    title: 'Limpiar toda la casa',
    description: 'Gran limpieza profunda de toda la casa',
    assigneeId: '1',
    completed: false,
    color: 'orange',
    rotation: -3,
    createdAt: new Date(),
    difficulty: 'épica',
  },
  {
    id: '6',
    title: 'Hacer la cama',
    description: 'Cambiar las sábanas también',
    assigneeId: '4',
    completed: false,
    color: 'yellow',
    rotation: 1,
    createdAt: new Date(),
    difficulty: 'básica',
  },
]
